### ISSUE TITLE
[BE] AI 기상 인증 관련 요청

### ISSUE THREAD

**Issue by srcho01** [kookmin-sw/capstone-2024-16#5]
프론트에서 백엔드로 좌표를 보내주면 AI 기상 인증방에 있는 유저들 데이터베이스에 좌표 저장해주세요.
AI에서 좌표 재설정이 필요하다고 판단하는 경우 좌표가 업데이트될 예정입니다.

**Comment by gyur2** [comment]
넹 구현 완료
